### ISSUE TITLE
新功能关于朋友圈屏蔽

### ISSUE THREAD

**Issue by whyliam** [shenm233/WechatMOD#1]
几乎每天上来看一次更新。
就是问问有没有可能实现朋友圈屏蔽的功能。
自己以前研究过一段时间，只怪自己水平有限，没有办法实现。

**Comment by shenm233** [comment]
朋友圈屏蔽?你想怎样屏蔽朋友圈

**Comment by whyliam** [comment]
关键字屏蔽 和 重复内容刷屏屏蔽（比如很多人都在转发同一个内容，就保留其中的一两个，其他的就屏蔽掉）

**Comment by shenm233** [comment]
这个实现起来非常困难。你要反编译，找出相关代码（经过混淆后的）才能实现，光找出来已经很不容易了。
