### ISSUE TITLE
有一个注入点找不到，求教

### ISSUE THREAD

**Issue by aviraxp** [shenm233/WechatMOD#10]
```
     private static void init(int idx, LoadPackageParam lpparam) throws Throwable {
              color.action_bar_color = new int[]{2131231144, 2131231131}[idx];
```

这里的字符串是怎么找到的？不胜感激。

**Comment by shenm233** [comment]
你留意一下有一处是调用actionbar的setDrawable/setColor来猜测这个颜色id。时间久远已经忘了具体的。

**Comment by aviraxp** [comment]
`this.jA.setBackgroundDrawable((Drawable)new ColorDrawable(this.getResources().getColor(2131231144)));`

找到了，谢谢。昨天搜索时候复制错了。

**Comment by aviraxp** [comment]
对了，你介意将V2打包发布吗？

**Comment by shenm233** [comment]
随你所意。

2016年9月16日 13:53，"Wang Han" notifications@github.com写道：
