### ISSUE TITLE
有没有考虑将抽屉加在ActionBar之上？

### ISSUE THREAD

**Issue by seasonyuu** [shenm233/WechatMOD#5]
RT

**Comment by shenm233** [comment]
曾经考虑过，但是现在停止维护。

**Comment by seasonyuu** [comment]
出现了什么问题吗？？我现在正fork了你的项目尝试把抽屉置于ActionBar之上

**Comment by shenm233** [comment]
现在有点害怕它会引起微信官方的注意，担心落得珊瑚虫qq的下场。
你可以改，最好自己用吧。

**Comment by shenm233** [comment]
stackoverflow有把抽屉置于ActionBar之上的技巧。

**Comment by seasonyuu** [comment]
我在自己的应用上面成功了  但是微信的ActionBar并不能当做普通的ActionBar来尝试

**Comment by shenm233** [comment]
微信的ActionBar是由兼容库提供的。

**Comment by seasonyuu** [comment]
这个库应该是由他自己实现的 暂时没什么思路 本来还想用ScrimInsetFrameLayout

**Comment by shenm233** [comment]
把ActionBar这个view remove出来，把它放在别的FrameLayout试试
