### ISSUE TITLE
看不懂代码

### ISSUE THREAD

**Issue by mountainguan** [shenm233/WechatMOD#6]
startMainUI = new String[]{"aKw", "aLJ", "aNp", "aNr", "aPu"}[idx]; /_"on main tab create"_/
像上面这些aKw，aLJ怎么来的，是反编译微信找到对应模块看吗？

**Comment by shenm233** [comment]
是的，粗略搜索注释里面的内容就能找到

不过，我做的注释并不完整

**Comment by mountainguan** [comment]
@shenm233 家里的电脑没有SDK又没有ADB= =，没得反编译，心好累~你快点更新吧

**Comment by shenm233** [comment]
不会更新的
2015年10月1日 23:31，"mountainguan" notifications@github.com写道：

**Comment by mountainguan** [comment]
好吧~那我有空研究一下自己鼓捣鼓捣
