### ISSUE TITLE
关于v2版本的建议

### ISSUE THREAD

**Issue by seasonyuu** [shenm233/WechatMOD#9]
突然在时间线看到你又开始写新版本了。关于新版本我clone下来跑了一遍发现是顶部Tab的设计。有没有想过采用MD规范中新出现的Bottom Navigation ？？现在感觉底部导航的确会更符合微信的使用习惯

**Comment by shenm233** [comment]
目前没有任何计划继续做，那天只不过一时兴起弄了一下。
说实在，感觉微信用上谷歌官方的material bottom navigation还是不搭配。还有xposed的限制不能直接用design
library，因为LayoutInflater没法通过反射调用模块的design library。

**Comment by seasonyuu** [comment]
我也主要是来看看你的意向，想实现肯定能实现的，Bottom
Nav并不错存在于最新版本的design库中，只能参考下其他开发者的开源实现，不过既然你也还没打算重拾这个项目，那就当我只是这么一提吧哈哈
On Apr 27, 2016 18:58, "shenm233" notifications@github.com wrote:

目前没有任何计划继续做，那天只不过一时兴起弄了一下。
说实在，感觉微信用上谷歌官方的material bottom navigation还是不搭配。还有xposed的限制不能直接用design
library，因为LayoutInflater没法通过反射调用模块的design library。
